INSERT INTO `test_subgroups` (`Subgroup_name`) VALUES ('MPN Instruments');
SET @subgroup_id := LAST_INSERT_ID();
-- SET @subgroup_id := 3;

INSERT INTO `test_names` (`Test_name`, `Full_name`, `Sub_group`) VALUES
  ('minors_ses_questionnaire', 'MINORS SES Questionnaire', 1),
  ('demographics_adult', 'Demographics Adult', 1),
  ('patient_health_questionnaire_9', 'Patient Health Questionnaire 9', 1),
  ('general_self_efficacy', 'General Self Efficacy', 1),
  ('social_participation_questionnaire_ccna', 'Social Participation Questionnaire (CCNA)', 1),
  ('d_curiosity_scale', '5D Curiosity Scale', 1),
  ('general_medical_profile', 'General Medical Profile', 1),
  ('alcohol_use_disorders_identification_testconcise_a', 'Alcohol Use Disorders Identification Testconcise A', 1),
  ('perceived_stress_questionnaire', 'Perceived Stress Questionnaire', 1),
  ('big_five10', 'Big Five-10', 1),
  ('physical_activity', 'Physical Activity', 1),
  ('epworths_sleepiness_scale', 'Epworth''s Sleepiness Scale', 1),
  ('pittsburg_sleep_quality_index_psqi', 'Pittsburg Sleep Quality Index Psqi', 1),
  ('aseba_asr_1859', 'Aseba Asr 1859', 1),
  ('puberty_scale', 'Puberty Scale', 1),
  ('q1k_eeg', 'Q1K EEG', 1),
  ('handedness_0f189a', 'Handedness', 1),
  ('music_history', 'Music History', 1),
  ('aseba_abcl_1859', 'Aseba Abcl 1859', 1),
  ('ucla_loneliness3', 'UCLA Loneliness-3', 1),
  ('moca', 'MOCA', 1),
  ('fagerstrm_test_for_nicotine_dependence_ftnd', 'FAGERSTRÖM TEST FOR NICOTINE DEPENDENCE (FTND)', 1),
  ('q1k_srs_adult_self_report_19_control_validation', 'Q1K SRS Adult Self Report 19 Control Validation', 1),
  ('q1k_srs_school_age', 'Q1K SRS School Age', 1),
  ('satisfaction_with_life_scale_swls', 'SATISFACTION WITH LIFE SCALE (SWLS)', 1),
  ('q1k_aseba_cbcl_618', 'Q1K ASEBA CBCL 618', 1),
  ('stroop', 'Stroop', 1),
  ('meaning_of_life_questionnaire', 'Meaning of Life Questionnaire', 1),
  ('the_cognitive_leisure_activity_scale_clas', 'THE COGNITIVE LEISURE ACTIVITY SCALE (CLAS)', 1),
  ('rand36_quality_of_life', 'RAND-36 Quality of Life', 1),
  ('incomplete_language_experience_and_proficiency_que', 'INCOMPLETE_LANGUAGE EXPERIENCE AND PROFICIENCY QUESTIONNAIRE (LEAP-Q)', 1),
  ('handedness', 'Handedness', 1),
  ('chailab_stress_parent_translated', 'Chailab_Stress_Parent_translated', 1),
  ('cognitive_reserve_index', 'Cognitive Reserve Index', 1),
  ('drug_abuse_screening_test_dast10', 'DRUG ABUSE SCREENING TEST (DAST10)', 1),
  ('screen_usage', 'Screen Usage', 1),
  ('chailab_stress_kids', 'Chailab_stress_kids', 1),
  ('generalized_anxiety_disorder_7_item_gad_7_scale', 'Generalized Anxiety Disorder 7 Item (GAD 7) Scale', 1),
  ('q1k_wais', 'Q1K WAIS', 1);
